trigger:
  - main

pool:
  name: Default

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python Addition.java
    displayName: 'Run java Script'
