trigger:
  - main

pool:
  name: Default

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'  # Change this to your required Java version
      jdkArchitecture: 'x64'

  - script: |
      javac Addition.java
      java Addition
    displayName: 'Compile and Run Java Program'

